### ISSUE TITLE
Error: Namespace object has no attribute 'wait_result'

### ISSUE THREAD

**Issue by MWFIAE** [ElrondNetwork/elrond-sdk#319]
It seems like there is an issue with the deploy command in newer erdpy releases.
Downgrading to older versions like 1.0.11 does fix the error.

```
Command:
 
erdpy --verbose contract deploy --project=mycounter --pem="devnet.pem" --gas-limit=5000000 --proxy="https://testnet-api.elrond.com" --outfile="counter.json" --recall-nonce --send
 
Error:
 
INFO:accounts:Account.sync_nonce()
INFO:accounts:Account.sync_nonce() done: 0
INFO:cli.contracts:Contract address: <censored>
Traceback (most recent call last):
  File "/home/<censored>/elrondsdk/erdpy", line 8, in <module>
    sys.exit(main())
  File "/home/<censored>/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli.py", line 31, in main
    _do_main()
  File "/home/<censored>/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli.py", line 55, in _do_main
    args.func(args)
  File "/home/<censored>/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli_contracts.py", line 181, in deploy
    result = _send_or_simulate(tx, args)
  File "/home/<censored>/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli_contracts.py", line 299, in _send_or_simulate
    send_wait_result = args.wait_result and args.send and not args.simulate
AttributeError: 'Namespace' object has no attribute 'wait_result'
```

**Comment by MWFIAE** [comment]
Fixed with the new version :)
