### ISSUE TITLE
crowdfunding contract error when deploying

### ISSUE THREAD

**Issue by erenakyildiz-code** [ElrondNetwork/elrond-sdk#337]
Hello,

i am trying to run the crowdfunding-egld template contract, but i am getting an error when i try to run the snippet "deploy simulate" or "deploy"

this is the error message: 

Traceback (most recent call last):
  File "/home/eren/elrondsdk/erdpy-venv/bin/erdpy", line 8, in <module>
    sys.exit(main())
  File "/home/eren/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/home/eren/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 56, in _do_main
    args.func(args)
  File "/home/eren/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli_contracts.py", line 185, in deploy
    contract = _prepare_contract(args)
  File "/home/eren/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli_contracts.py", line 224, in _prepare_contract
    if len(args.bytecode):
TypeError: object of type 'NoneType' has no len()

thanks in advance.

**Comment by erenakyildiz-code** [comment]
Thanks to Martin Wagner i have the answer:

change the devnet.snippets.sh deploySimulate to:

deploySimulate() {
    erdpy --verbose contract deploy --bytecode="${PROJECT}/output/my_crowdfunding.wasm" --recall-nonce --pem=${ALICE} \
          --gas-limit=${DEPLOY_GAS} --arguments ${DEPLOY_ARGUMENTS} \
          --outfile="simulate-devnet.interaction.json" --simulate || return

    TRANSACTION=$(erdpy data parse --file="simulate-devnet.interaction.json" --expression="data['result']['hash']")
    ADDRESS=$(erdpy data parse --file="simulate-devnet.interaction.json" --expression="data['emitted_tx']['address']")
    RETCODE=$(erdpy data parse --file="simulate-devnet.interaction.json" --expression="data['result']['returnCode']")
    RETMSG=$(erdpy data parse --file="simulate-devnet.interaction.json" --expression="data['result']['returnMessage']")

    echo ""
    echo "Simulated transaction: ${TRANSACTION}"
    echo "Smart contract address: ${ADDRESS}"
    echo "Deployment return code: ${RETCODE}"
    echo "Deployment return message: ${RETMSG}"
}
